plugins {
    id 'java'
}

group = 'net.zithium'
version = '3.17.21'

description = 'XLTournaments'

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(21))
}

repositories {
    mavenCentral()

    maven { url = uri("https://repo.papermc.io/repository/maven-public/") }
    maven { url = uri('https://oss.sonatype.org/content/groups/public') }
    maven { url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/') }
    maven { url = uri('https://jitpack.io') }
    maven { url = uri('https://raw.githubusercontent.com/TeamVK/maven-repository/master/release/') }
    maven { url = uri('https://repo.codemc.io/repository/maven-public/') }
    maven { url = uri('https://mvn.lumine.io/repository/maven-public/') } // MythicMobs
    maven { url = uri('https://repo.extendedclip.com/content/repositories/placeholderapi/') }
    maven { url = uri('https://repo.essentialsx.net/releases/') }
    maven { url = uri('https://libraries.minecraft.net/') }
}

dependencies {
    // Runtime libraries are provided by Paper's library loader (see plugin.yml `libraries`).
    compileOnly('com.zaxxer:HikariCP:5.1.0')
    compileOnly('me.mattstudios.utils:matt-framework:1.4.6')
    compileOnly("com.github.cryptomorin:XSeries:13.7.0")

    compileOnly('dev.triumphteam:triumph-gui:3.1.13')

    compileOnly('org.bstats:bstats-bukkit:3.0.2')

    // Adventure
    compileOnly "net.kyori:adventure-text-minimessage:4.24.0"

    // Apache
    compileOnly 'org.apache.commons:commons-lang3:3.12.0'

    compileOnly 'io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT'
    compileOnly 'com.mojang:authlib:1.5.21'

    // EXTERNAL OBJECTIVES
    //compileOnly 'com.github.electro2560:ClueScrollsAPI:c5f0b7aa3a' // ClueScrolls
    compileOnly 'com.github.Realizedd.Duels:duels-api:3.5.1' // Duels
    compileOnly 'com.github.MilkBowl:VaultAPI:1.7.1' // Vault
    //compileOnly 'com.vk2gpz.tokenenchant:TokenEnchantAPI:23.9.0' // TokenEnchant
    compileOnly 'me.clip:placeholderapi:2.11.5' // PlaceholderAPI
    compileOnly 'com.github.NuVotifier:NuVotifier:2.7.2' // nuVotifier
    compileOnly 'io.lumine:Mythic-Dist:5.6.1' // MythicMobs
    compileOnly 'net.essentialsx:EssentialsX:2.20.1' // EssentialsX
    compileOnly fileTree(dir: 'libs', include: '*.jar') // libs folder.
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
